<?php
  /**
   * @file
   * A subscription for the new/changed/updated content on the site.
   */

  /**
   * Implements hook_help().
   */
  function subscribe_help($path, $arg) {
    switch($path) {
      case 'admin/help#subscribe':{
        $ret_val = '<h3>' . t('About') . '</h3>';
        $ret_val .= '<p>' . t('The Subscribe module allows users to receive emails when there are updates to site content') . '</p>';
        return $ret_val;
        break;
      }
    }
  }

  /**
   * Implements hook_permission().
   */
  function subscribe_permission() {
    return array(
      'administer subscribe' => array (
        'title' => t('Administer Subscribe'),
        'description' => t('Perform administrative tasks on Subscribe functionality'),
      ),
    );
  }

  /**
   * Implements hook_menu().
   */
  function subscribe_menu() {
    $items = array();

    //Admin configuration group.
    $items['admin/config/subscribe'] = array(
      'title' => 'Subscribe',
      'description' => 'Administer Subscribe',
      'access arguments' => array('administer subscribe'),
    );

    //Admin configuration - Settings.
    $items['admin/config/subscribe/manage'] = array(
      'title' => 'Subscribe settings',
      'description' => 'Manage Subscribe settings and configurations',
      'access arguments' => array('administer subscribe'),
      'page callback' => 'drupal_get_form',
      'page arguments' => array('subscribe_admin_settings_form'),
    );

    return $items;
  }

  /**
   * Implements hook_form().
   */
  function subscribe_admin_settings_form($node, &$form_state) {
    $form = array();

    // The site's content types
    $select = array();
    $select[0] = '<' . t('none') . '>';
    $nodetypes = node_type_get_types();
    foreach ($nodetypes as $ntype => $nname) {
      $select[$ntype] = $nname->name;
    }

    $form['overview'] = array(
      '#markup' => t('This interface allows administrators to manage general Subscribe settings'),
      '#prefix' => '<p>',
      '#suffix' => '</p>',
    );

    $form['subscribe_select_content_types'] = array(
      '#type'          => 'select',
      '#title' => t('Subscription Content Types'),
      '#description' => t('The Content Types that users can subscribe to'),
      '#default_value' => variable_get('subscribe_select_content_types'),
      '#options' => $select,
      '#multiple' => TRUE,
      '#required' => TRUE,
    );

    return system_settings_form($form);
  }

  /**
   * @param $form
   * @param $form_state
   *
   * Validates Subscribe admin settings.
   */
  function subscribe_admin_settings_form_validate($form, &$form_state) {
    //

  }


